### ISSUE TITLE
How to set up redirectUrl?

### ISSUE THREAD

**Issue by yakirifrah** [MeixDev/DiscordManager#4]
Hi @MeixDev i need help what i need to set up in redirect URL so after authorization route to app and not URL?

**Comment by MeixDev** [comment]
Hello ! You need to create a custom-made protocol/scheme for both your Android and iOS apps and use that as your redirection so your app can catch it. You can get a few more infos about it here : [Flutter Deep Linking Documentation](https://flutter.dev/docs/development/ui/navigation/deep-linking)

DiscordManager uses the uni_links package to do it, and as said in the description of the package, it needs some tinkering with your AndroidManifest.xml and your Info.plist in order to work. The pub dev page is here : [uni_links](https://pub.dev/packages/uni_links)

I haven't worked or even touched on the DiscordManager for months, so if anything is broken on either Discord's side or uni_links' side because of new versions of both Android and iOS, please let me know so I can't take a look at it.

Finally, if you intend to publish a web application as well, this plugin cannot help you directly, I however worked with a friend on some solutions, for the Twitch API this time, that you can easily adapt to the Discord API. The medium articles are available : [here](https://itnext.io/flutter-web-twitch-oauth2-authentication-flow-implementation-77d239c72be5) and [here](https://itnext.io/flutter-web-oauth-authentication-through-external-window-d890a7ff6463) !

**Comment by yakirifrah** [comment]
Hello! @MeixDev thank you a lot for your input, I decided in the end to create a service on node js for authentication with discord, so maybe i need to tinker with  deeplinks mechanism 🤓

**Comment by MeixDev** [comment]
You'll very probably have to, otherwise you won't be able to open up your app from your auth service.

Closing issue, then!
